package test;

public class DwdTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_test.user_name
     *
     * @mbggenerated Wed Jun 08 11:41:25 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_test.user_id
     *
     * @mbggenerated Wed Jun 08 11:41:25 CST 2016
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_test.user_name
     *
     * @return the value of dwd_test.user_name
     *
     * @mbggenerated Wed Jun 08 11:41:25 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_test.user_name
     *
     * @param userName the value for dwd_test.user_name
     *
     * @mbggenerated Wed Jun 08 11:41:25 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_test.user_id
     *
     * @return the value of dwd_test.user_id
     *
     * @mbggenerated Wed Jun 08 11:41:25 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_test.user_id
     *
     * @param userId the value for dwd_test.user_id
     *
     * @mbggenerated Wed Jun 08 11:41:25 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}