package test;

import java.util.List;
import test.DwdTest;
import test.DwdTestExample;

public interface DwdTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_test
     *
     * @mbggenerated Wed Jun 08 11:41:25 CST 2016
     */
    int insert(DwdTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_test
     *
     * @mbggenerated Wed Jun 08 11:41:25 CST 2016
     */
    int insertSelective(DwdTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_test
     *
     * @mbggenerated Wed Jun 08 11:41:25 CST 2016
     */
    List<DwdTest> selectByExample(DwdTestExample example);
}